apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world - concurrency test"
  test:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world - duplicate - concurrency test"
  manual-approval:
    with:
      approvers: e70bcb3e-4a74-11ed-b1a3-42010a83ae66
      disallowLaunchByUser: false
      instructions: click me
    # timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/.cloudbees/testing/custom-job.yml@CBP-9365
  deploy:
    needs: manual-approval
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world - duplicate - deploy - 1"
